// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwoilgpbxxzjzpltosas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3b2lsZ3BieHh6anpwbHRvc2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwMTMwNDcsImV4cCI6MjA5NTU4OTA0N30.sN9rsxat2Vo-D8xhsZ5UzgLw3zhKRhjcepzZgdwAqZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});